[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
fuzz = { runs = 256 }
invariant = { runs = 256 }
gas_reports = ["PredictionMarket"]

[profile.ci]
fuzz = { runs = 1000 }
invariant = { runs = 1000 }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

# RPC Endpoints
[rpc_endpoints]
sepolia = "${ETHEREUM_SEPOLIA_RPC}"
base_sepolia = "${BASE_SEPOLIA_RPC}"
polygon_amoy = "${POLYGON_AMOY_RPC}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC}"
optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC}"
bsc_testnet = "${BSC_TESTNET_RPC}"
ethereum = "${ETHEREUM_MAINNET_RPC}"
base = "${BASE_MAINNET_RPC}"
polygon = "${POLYGON_MAINNET_RPC}"
arbitrum = "${ARBITRUM_MAINNET_RPC}"
optimism = "${OPTIMISM_MAINNET_RPC}"
bsc = "${BSC_MAINNET_RPC}"

# Etherscan / Verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }
base_sepolia = { key = "${BASESCAN_API_KEY}", chain = 84532, url = "https://api-sepolia.basescan.org/api" }
polygon_amoy = { key = "${POLYGONSCAN_API_KEY}", chain = 80002 }
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}", chain = 421614 }
optimism_sepolia = { key = "${OPSCAN_API_KEY}", chain = 11155420 }
bsc_testnet = { key = "${BSCSCAN_API_KEY}", chain = 97 }
bsc = { key = "${BSCSCAN_API_KEY}", chain = 56 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
